### PR TITLE
Simply Simplates

### LINKED ISSUE #526: join 'em
If you can't beat 'em, join 'em. This ticket started (per the original description below) by thinking that we'd kill the Aspen project/brand and reemerge as Simplates, a plugin for Django and Flask. We took a step [back](https://github.com/gratipay/aspen.py/issues/526#issuecomment-172959647) from the brink when we realized that Aspen is *dispatch plus* simplates, and it's worth keeping Aspen for the amalgamation. The basic idea is the same, though: Aspen is becoming a "parasitic web framework," a plugin for Django and Flask.

-----------------

Okay! Wow! Over on the [November 2015 call](https://github.com/gratipay/aspen.py/issues/525), @pjz  and I began talking about the Python 3 port (#524), which led back to the discussion about switching to Werkzeug (see #222 and mention on #357), and then expanded even further: What is the essence of Aspen? Answer: dispatch and simplates. What if we cut out everything non-essential? What if we killed Aspen as a brand and instead folded the dispatcher into [Simplates](), offering shims for Django and Flask?

Django and Flask are the Python web frameworks of record, with Pyramid/Pylons leading the also-rans:

| Framework | PyPI Downloads | PyPI Rank |
|:----------------|----------------:|---------:|
| [Django](http://pypi-ranking.info/module/Django) | 16,128,764&nbsp; | 26&nbsp; |
| [Flask](http://pypi-ranking.info/module/Flask) | 10,290,820&nbsp; | 45&nbsp; |
| [Pyramid]() + [Pylons](http://pypi-ranking.info/module/Pylons) | 2,055,805<sup>†</sup> | 212<sup>†</sup> |
| [Bottle](http://pypi-ranking.info/module/Bottle) | 1,513,060&nbsp; | 260&nbsp; |
| [Aspen](http://pypi-ranking.info/module/Aspen) | 918,591&nbsp; | 362&nbsp; |
| [Zope2](http://pypi-ranking.info/module/Zope2) + [zope.publisher](http://pypi-ranking.info/module/zope.publisher) | 884,100<sup>†</sup> | 368<sup>†</sup> |
| [CherryPy](http://pypi-ranking.info/module/CherryPy) | 749,732&nbsp; | 410&nbsp; |
| [web.py](http://pypi-ranking.info/module/web.py) | 437,894&nbsp; | 604&nbsp; |

<sup>†</sup> *combined*

The proposal on this ticket is to throw in the towel. Give up. Call it a day. Admit defeat. Stop writing a web framework.

Instead, we would take the most interesting parts of what we've built—simplates and the filesystem dispatcher—and repackage them under the [Simplates](http://simplates.org/) brand. Simplates and dispatch *are* interesting and unique. We've already got a [shim for Django](https://gist.github.com/whit537/1ccf19dc5bd95363564d). We should be able to adapt that for Flask without too much trouble, so the `simplates` library would look something like this:

```
simplates
simplates.dispatch
simplates.renderers
simplates.resources
simplates.shims.django
simplates.shims.flask
```

This would allow us to invest our time and effort where we're really adding value, and collaborate with others where we're currently reinventing the wheel.

### PR DESCRIPTION
**Pull request by whit537**
Closes #526.

### CODE REVIEW

**Comment by whit537** [comment]
Rebased on master. I've taken a couple stabs at this, and I think the best way to proceed is going to be to chip away at the `aspen/algorithms/website.py` algorithm bit by bit, until it only contains what we want for Simplate processing. We may end up shipping algorithm.py with Simplates after all, but with no HTTP handling.

**Comment by pjz** [comment]
Need example code for new use case: what does an aspen-flask app look like? Django-flask?  Instead of` aspen.shim.flask` maybe it should be a flask-aspen package that depends on aspen (or some new 'aspen-core') and flask?  Same for a django-aspen package?

**Comment by whit537** [comment]
> Need example code for new use case: what does an aspen-flask app look like?

Dunno. We do have [some Django code](https://gist.github.com/whit537/1ccf19dc5bd95363564d), of course.

> Django-flask?

:nut_and_bolt: 

> Instead of` aspen.shim.flask` maybe it should be a flask-aspen package that depends on aspen (or some new 'aspen-core') and flask?  Same for a django-aspen package?

Yeah, maybe. However, Django and Flask are [clearly](https://github.com/gratipay/aspen.py/issues/526#issue-115318565) the Coke and Pepsi of the Python web world. Since Simplates is intended to be used with an existing web framework, I think it probalby makes sense to ship shims for those two.

**Comment by pjz** [comment]
>>Instead of aspen.shim.flask maybe it should be a flask-aspen package that depends on aspen (or some new 'aspen-core') and flask? Same for a django-aspen package?
>
>Yeah, maybe. However, Django and Flask are clearly the Coke and Pepsi of the Python web world. Since Simplates is intended to be used with an existing web framework, I think it probably makes sense to ship shims for those two.

I agree, I was just noticing that if we make them separate packages then the dependencies fall out correctly:
  * `flask-aspen` contains the shim and depends on `flask` and `aspen`
  * `django-aspen` contains the shim and depends on `django` and `aspen`

It also makes it clear how to proceed with other shims.

That said, they can all be in the same repo.

**Comment by whit537** [comment]
@pjz Okay, let's revisit that when we're further along. For now I think these are our next steps:

 - Remove all uses of `harness.client.{GET,GxT,POST,PxST}` in the test suite, or replace them with `harness.simple`.
 - Teach the dispatcher tests to work without HTTP.
 - Modify `Website.respond` and `algorithms.website` to not depend on HTTP request and response objects.
 - Change `Website` into something like `SimplateManager`, with `harness.simple` following suit.
 - Remove `http.*`.

**Comment by whit537** [comment]
I've got this just about ready for review. All of the demolition and clearing out is done, and I've barely started into refactoring: we now have a  `Processor` object (it was the `Website` object), which has a `process` method that takes a path, a querystring, an accept header, and returns an `Output` object (cf. Aspen's `Response` object) with body, media_type, and charset attributes.

@pjz @Changaco et al. How would you like to proceed from here? This is a big PR. There's a little more brush-clearing that could go on here (removing the old docs, Procfile, etc.). But from this point I would expect to launch into a round of refactoring together with writing documentation to end up with a high quality product. In other words, this is the moment we (I) have been waiting for! :-)

Do you want to land this PR first, and then launch into the refactoring and documenting? Or shall I proceed with that on this PR?

**Comment by whit537** [comment]
> `ImportError: No module named aspen.testing`

Why can't AppVeyor find `aspen.testing`? :-/

**Comment by pjz** [comment]
I'm a little reluctant to land this until we have `flask-aspen` to 1) show how to use it, 2) verify that it works, 3) (and perhaps most importantly) have a valid forward migration path for (admittedly, perhaps illusory) users. If we land this now, there's no clear way to use it. When we switched to pure WSGI, we could at least doc how to use it and even provide a minimal server (python -m aspen). We should do the same now.

**Comment by Changaco** [comment]
I agree with @pjz. Note: not everything has to be put directly in this PR, making additional PRs that target the `just-simplates` branch could ease the review process.

**Comment by whit537** [comment]
Okay, sounds like a plan! :-)

**Comment by whit537** [comment]
Looks like AppVeyor broke in 034acd0047177ffefa3942af6e4e8fa063b56152 or cf838d0a4e88c253d0827e849b3f212d1c772eb3.

screen shot 2015-11-25 at 12 23 04 pm

**Comment by whit537** [comment]
It only fails on Windows. Linux (Travis) and Mac OS are fine.

**Comment by whit537** [comment]
All four AppVeyor builds failed in the same way.

**Comment by whit537** [comment]
Can we run 034acd0047177ffefa3942af6e4e8fa063b56152 through AppVeyor to narrow down the failure range?

**Comment by whit537** [comment]
https://ci.appveyor.com/project/gratipay/aspen-py/build/106/job/6r8e3dk7ly9wu6r6#L1190

```
==============================================================================
sys.path:
  C:\projects\aspen-py\tests
  C:\projects\aspen-py\env\Scripts\py.test.exe
  C:\windows\SYSTEM32\python27.zip
  c:\projects\aspen-py\env\DLLs
  c:\projects\aspen-py\env\lib
  c:\projects\aspen-py\env\lib\plat-win
  c:\projects\aspen-py\env\lib\lib-tk
  c:\projects\aspen-py\env\scripts
  C:\Python27\Lib
  C:\Python27\DLLs
  C:\Python27\Lib\lib-tk
  c:\projects\aspen-py\env
  c:\projects\aspen-py\env\lib\site-packages
==============================================================================
```

**Comment by whit537** [comment]
Can we import `aspen` at that point? Maybe it's a problem with `aspen.testing` specifically?

**Comment by whit537** [comment]
It's [not specific to `aspen.testing`](https://ci.appveyor.com/project/gratipay/aspen-py/build/108/job/s3werupqeaw83emy#L1256):

```
ImportError: No module named aspen
```

**Comment by whit537** [comment]
Perhaps AppVeyor made a change?

**Comment by whit537** [comment]
> Can we run 034acd0047177ffefa3942af6e4e8fa063b56152 through AppVeyor to narrow down the failure range?

I went back to 034acd0047177ffefa3942af6e4e8fa063b56152 and force-pushed it here to trigger an AppVeyor build.

**Comment by whit537** [comment]
Looks like it's working.

**Comment by Changaco** [comment]
Your `sys.path` dump shows you the problem: `C:\projects\aspen-py` isn't in it.

**Comment by whit537** [comment]
> Your `sys.path` dump shows you the problem: `C:\projects\aspen-py` isn't in it.

I noticed that. But why is that the problem? Why did cf838d0a4e88c253d0827e849b3f212d1c772eb3 cause that to happen?

**Comment by whit537** [comment]
Interesting! I don't see the output of 2fe1ece9910209345d42c22fd8ae0d033ac248d4 at all in https://ci.appveyor.com/project/gratipay/aspen-py/build/113/job/uncfflrw8qjb6nqd!

**Comment by Changaco** [comment]
> Why did cf838d0 cause that to happen?

Maybe it didn't.

Concerning the solution, the one I use in Liberapay's Makefile is to set `PYTHONPATH=.`.

**Comment by whit537** [comment]
Okay, leaving off with this for now, will pick up again in a bit ...

**Comment by whit537** [comment]
Decided on the call this morning (#528) to include a Flask and/or Django shim directly on master as part of this PR. That way we can land it sooner rather than later and it'll still be useful in the real world. Then we can look at where to carve the joints. Maybe, for example, we keep the Aspen brand as a "filesystem dispatcher for Flask and Django," and it uses a factored-out Simplates as a library.

**Comment by whit537** [comment]
Found it. cf838d0a4e88c253d0827e849b3f212d1c772eb3 caused the `import aspen` [check](https://github.com/gratipay/aspen.py/blob/cf838d0a4e88c253d0827e849b3f212d1c772eb3/build.py#L84) in `build.py` to fail in such a way that `found` was in the traceback output, which confused the subsequent `if b'found' in v` condition.

Here's how `import aspen` fails under 034acd0047177ffefa3942af6e4e8fa063b56152:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aspen/__init__.py", line 70, in <module>
    from .http.response import Response
  File "aspen/http/response.py", line 15, in <module>
    from ..utils import ascii_dammit
  File "aspen/utils.py", line 15, in <module>
    import algorithm
ImportError: No module named algorithm
```

Here's how it fails under cf838d0a4e88c253d0827e849b3f212d1c772eb3:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aspen/__init__.py", line 76, in <module>
    dist = pkg_resources.get_distribution('aspen')
  File "/Users/whit537/personal/gratipay/simplates.py/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 551, in get_distribution
    dist = get_provider(dist)
  File "/Users/whit537/personal/gratipay/simplates.py/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 431, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Users/whit537/personal/gratipay/simplates.py/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/whit537/personal/gratipay/simplates.py/env/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aspen' distribution was not found and is required by the application
```

Fixed in db48b80cac8d2a6dceb100bf2a5e80ffc7e630c0.

**Comment by whit537** [comment]
Here's what I used to test this:

```bash
alias test="make clean && deactivate && rm -rf aspen.egg-info/ && python2 build.py dev && source env/bin/activate && py.test tests/"
```

Presumably Travis caches the `aspen.egg-info/` directory, whereas AppVeyor does not.

**Comment by whit537** [comment]
Hrm ... looks like I haven't quite solved this yet.

**Comment by whit537** [comment]
Maybe we can use [`precedence`](https://pythonhosted.org/setuptools/pkg_resources.html#distribution-attributes)?

**Comment by whit537** [comment]
I have `aspen.py/` on my local `PYTHONPATH`, and I can't find where it's coming from. The `pkg_resources.get_distribution` call is finding it. I've renamed the directory as a workaround.

**Comment by whit537** [comment]
With that, db48b80cac8d2a6dceb100bf2a5e80ffc7e630c0 is [passing](https://github.com/gratipay/aspen.py/pull/527#issuecomment-162539312) for me locally. Why is it still failing at AppVeyor?

**Comment by pjz** [comment]
I wonder if something is behaving badly because the repo name has a dot in it on windows?

**Comment by whit537** [comment]
Also, can we suppress the extra branch build on AppVeyor like we [do on Travis](https://github.com/gratipay/aspen.py/blob/0.42/.travis.yml#L2-L4)?

**Comment by whit537** [comment]
[Yes](http://www.appveyor.com/docs/branches#white-and-blacklisting)! :-)

**Comment by whit537** [comment]
@pjz [Looks like](https://ci.appveyor.com/project/gratipay/aspen-py/build/120/job/efeaqy1obhfw721x#L1324) we don't have a dot in the name after all.

**Comment by whit537** [comment]
`sys.path` in ddc3d1b8973d2e0c9be43207565d9cd3cdc1834e looks different than [before](https://github.com/gratipay/aspen.py/pull/527#issuecomment-159687553):

```
C:\projects\aspen-py
C:\Python27\lib\site-packages\aspen-0.42.dev0-py2.7.egg
C:\Python27\lib\site-packages\filesystem_tree-1.1.2-py2.7.egg
C:\Python27\lib\site-packages\algorithm-1.0.0-py2.7.egg
C:\Python27\lib\site-packages\first-2.0.1-py2.7.egg
C:\Python27\lib\site-packages\python_mimeparse-0.1.4-py2.7.egg
C:\Python27\lib\site-packages\dependency_injection-1.1.0-py2.7.egg
C:\windows\SYSTEM32\python27.zip
C:\Python27\DLLs
C:\Python27\lib
C:\Python27\lib\plat-win
C:\Python27\lib\lib-tk
C:\Python27
C:\Python27\lib\site-packages
```

**Comment by pjz** [comment]
Try changing the 'aspen was found' signifier string from 'found' to something more unique like 'aspen_was_found'

**Comment by whit537** [comment]
> Try changing the 'aspen was found' signifier string from 'found' to something more unique like 'aspen_was_found'

I did that at one point using `uuid`, but testing for whether Aspen is installed in that way seems like a code smell. I think the better solution is 6817da6b0b16b8367cf073b72a0b841dc57217d9. Let's see whether AppVeyor agrees. ;-)

**Comment by whit537** [comment]
Blam. :-)

You good with 6817da6b0b16b8367cf073b72a0b841dc57217d9, @pjz @Changaco? May I proceed to rebase the rest of this PR back onto the branch?

**Comment by pjz** [comment]
:+1:

**Comment by whit537** [comment]
Cool. I'll push a rebased cf838d0a4e88c253d0827e849b3f212d1c772eb3 to make sure that works, and then the rest of the commits all at once.

**Comment by whit537** [comment]
Okay! Now that this PR is green I'll proceed with additional PRs against `just-simplates` as [discussed](https://github.com/gratipay/aspen.py/pull/527#issuecomment-159208270).

**Comment by Changaco** [comment]
Note: `pkg_resources.get_distribution` is not reliable way to get the version number. If we want to have a single source of truth for the version number I recommend getting it from git tags, using [setuptools_scm](https://pypi.python.org/pypi/setuptools_scm) or my own [version.py](https://github.com/Changaco/version.py).

**Comment by whit537** [comment]
@Changaco Cool, thanks. Looks like we're still using a `version.txt` file for versioning info. I was only looking at `pkg_resources.get_distribution` as a way to see if Aspen was installed at all (regardless of version number), but ended up not using it all in 6817da6b0b16b8367cf073b72a0b841dc57217d9.

**Comment by Changaco** [comment]
To clarify, aspen is using `pkg_resources.get_distribution`, on master and [on this branch](https://github.com/gratipay/aspen.py/blob/just-simplates/aspen/__init__.py#L74). That's what I recommend changing.

**Comment by whit537** [comment]
Ah, of course. Thanks.

**Comment by whit537** [comment]
Alright! With #535 and #536 we've now got working, tested code for Django and Flask shims. I think the basic pieces are roughed in. Next steps are to make some decisions about some loose ends, merge the open PRs (#531 and #532 in addition to the above) down into this one, and then start reviewing this PR in earnest to bring it in for a landing.

**Comment by pjz** [comment]
Now we need flask and Django installed for all the tests to pass.  Do you really want to vendor them?

**Comment by whit537** [comment]
@pjz Thanks for the merges.

> Now we need flask and Django installed for all the tests to pass. Do you really want to vendor them?

No. I figured on looking into matrix testing at Travis and AppVeyor to test different version combinations.

**Comment by pjz** [comment]
Hmm.  A local 'make test' has one of the django tests failing with `E           AppRegistryNotReady: The translation infrastructure cannot be initialized before the apps registry is ready. Check that you don't make non-lazy gettext calls at import time.`

**Comment by whit537** [comment]
Punchlist:

 - [ ] fix tests and figure out Django and Flask dependencies ([Travis matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix))
 - [ ] update documentation
 - [ ] ... maybe something else from #529 that I forgot?
 - [ ] move renderers from plugins into the main repo for now (they should really become *simplates* plugins)

We talked about trying out squash-and-rebase to land this PR (vs. GitHub merge), in order to start keeping a cleaner history that can maybe drive our changelog in the future (#538).

**Comment by whit537** [comment]
Relevant:

https://docs.travis-ci.com/user/languages/python#Testing-Against-Multiple-Versions-of-Dependencies-(e.g.-Django-or-Flask)

and

https://docs.travis-ci.com/user/languages/python#Build-Matrix

**Comment by whit537** [comment]
A couple decisions out of #537:

 - [0:00](https://www.youtube.com/watch?v=k2dHW1EtG8A)—We decided not to support `python -m aspen` at all, to avoid confusing people with stunted software. Our quickstart will start with `pip install flask`.
 - [12:46](https://www.youtube.com/watch?v=k2dHW1EtG8A#t=12m46s)—We talked about our test matrix, and decided on these combinations:
  - Django 1.8.9 (latest LTS)
  - Django 1.9.2 (latest)
  - Flask 0.9 (previous; still in their sidebar) / Jinja2 2.4 (oldest supported) / latest Werkzeug
  - Flask 0.10.1 (latest) / Jinja2 2.8 (latest) / latest Werkzeug and itsdangerous

**Comment by whit537** [comment]
Not gonna lie: I'm gonna miss algorithm.py.

screen shot 2016-02-16 at 12 14 06 pm

**Comment by whit537** [comment]
Meh, if Flask turns out to suck we can always bring back our own request/response objects in Aspen 2.0. :-)

**Comment by whit537** [comment]
I'm being torn apart. I want to be free of this pain. I know what I have to do but I don't know if I have the strength to do it. Will you help me?

kylorenhansolo

**Comment by pjz** [comment]
Do I need to be the one to fix our CI so we can prove this passes the tests so we can then merge it?

**Comment by whit537** [comment]
@pjz Maybe! But now we should discuss how this PR relates to the latest on #526 and now #547.

cc: @Changaco

**Comment by Changaco** [comment]
Rebased on master.

I think the next step here is to move the Django and Flask bits to separate branches, because [the plan](https://github.com/AspenWeb/salon/issues/2) is to put them in their own repos, not in aspen-core.

**Comment by Changaco** [comment]
I've pushed this branch to [aspen-core.py](https://github.com/AspenWeb/aspen-core.py).

**Pull request closed without merging**
