### PR TITLE
rename to Pando

### PR DESCRIPTION
**Pull request by whit537**
Pursuant to https://github.com/AspenWeb/salon/issues/2#issuecomment-198513656.

### CODE REVIEW

**Comment by whit537** [comment]
I think this is ready for review, @Changaco. Should we remove the aspen.io website from this repo as part of this PR?

**Comment by Changaco** [comment]
You're referencing `pando.io` in a few places, we don't control that domain name.

**Comment by Changaco** [comment]
> Should we remove the aspen.io website from this repo as part of this PR?

Then we won't have it anywhere (except in the history of course), since you haven't copied it to the aspen.io repo, and it's already gone from aspen-core.

**Comment by Changaco** [comment]
I've added some commits, including 9b2e2d13325d1a79ba35d590f3f4e5131e1c6e7f from #527.

**Comment by whit537** [comment]
@Changaco Looks good to me.

**Pull request merged**
